const SelectionActions = {
    SET_SELECTED_MOVIE: "SET_SELECTED_MOVIE",
    SET_SELECTED_VENUE: "SET_SELECTED_VENUE",
    SET_SELECTED_SEATS: "SET_SELECTED_SEATS",
    FETCH_VENUES: "FETCH_VENUES",
    FETCH_VENUES_SUCCESS: "FETCH_VENUES_SUCCESS",
    FETCH_VENUES_FAILURE: "FETCH_VENUES_FAILURE",
    FETCH_AVAILABILITIES: "FETCH_AVAILABILITIES",
    FETCH_AVAILABILITIES_SUCCESS: "FETCH_AVAILABILITIES_SUCCESS",
    FETCH_AVAILABILITIES_FAILURE: "FETCH_AVAILABILITIES_FAILURE",
    MODIFY_AVAILABILITIES: "MODIFY_AVAILABILITIES",
    MODIFY_AVAILABILITIES_SUCCESS: "MODIFY_AVAILABILITIES_SUCCESS",
    MODIFY_AVAILABILITIES_FAILURE: "MODIFY_AVAILABILITIES_FAILURE"
};

export default SelectionActions;