const HomeActions = {
    FETCH_MOVIES: "FETCH_MOVIES",
    FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
    FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
    SET_SELECTED_MOVIE: "SET_SELECTED_MOVIE",
};

export default HomeActions;